# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-30 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180505_0922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='\u0417\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('slogan', models.CharField(help_text='\u041d\u0435 \u0431\u043e\u043b\u0435\u0435 100 \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u0432', max_length=500, verbose_name='\u0421\u043b\u043e\u0433\u0430\u043d')),
                ('description', models.TextField(verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('image', models.ImageField(help_text='\u0420\u0430\u0437\u043c\u0435\u0440 432x275', upload_to='images/slider', verbose_name='\u041a\u0430\u0440\u0442\u0438\u043d\u043a\u0430')),
                ('price', models.CharField(blank=True, max_length=255, null=True, verbose_name='\u0426\u0435\u043d\u0430 (\u0435\u0441\u043b\u0438 \u044d\u0442\u043e \u0442\u043e\u0432\u0430\u0440)')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
